CREATE TABLE PESSOA(ID INT PRIMARY KEY AUTO_INCREMENT, NOME VARCHAR(255), EMAIL VARCHAR(255), CPF VARCHAR(255), CNPJ VARCHAR(255),
DEPARTAMENTO VARCHAR(255), MATRICULA VARCHAR(255), TELEFONE VARCHAR(255), ENDERECO VARCHAR(255), NASCIMENTO VARCHAR(255), SOCIAL VARCHAR(255), CATEGORIA VARCHAR(255));

CREATE TABLE FORNECEDOR(ID INT PRIMARY KEY AUTO_INCREMENT, NOME VARCHAR(255), EMAIL VARCHAR(255), CNPJ VARCHAR(255),
TELEFONE VARCHAR(255), ENDERECO VARCHAR(255), NASCIMENTO VARCHAR(255), SOCIAL VARCHAR(255), CATEGORIA VARCHAR(255));

CREATE TABLE ALUNO(ID INT PRIMARY KEY AUTO_INCREMENT, NOME VARCHAR(255), EMAIL VARCHAR(255), CPF VARCHAR(255),
MATRICULA VARCHAR(255), TELEFONE VARCHAR(255), ENDERECO VARCHAR(255), NASCIMENTO VARCHAR(255));

CREATE TABLE PROFESSOR(ID INT PRIMARY KEY AUTO_INCREMENT, NOME VARCHAR(255), EMAIL VARCHAR(255),
DEPARTAMENTO VARCHAR(255), TELEFONE VARCHAR(255), ENDERECO VARCHAR(255), NASCIMENTO VARCHAR(255));

SELECT * FROM PESSOA;
SELECT * FROM FORNECEDOR;
SELECT * FROM ALUNO;
SELECT * FROM PROFESSOR;

INSERT INTO PESSOA NOME, EMAIL, CPF, CNPJ, DEPARTAMENTO, MATRICULA, TELEFONE, ENDERECO, NASCIMENTO, SOCIAL, CATEGORIA VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO FORNECEDOR NOME, EMAIL, CNPJ, TELEFONE, ENDERECO, NASCIMENTO, SOCIAL, CATEGORIA VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO ALUNO NOME, EMAIL, CPF, MATRICULA, TELEFONE, ENDERECO, NASCIMENTO VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO PROFESSOR NOME, EMAIL, CPF, DEPARTAMENTO, TELEFONE, ENDERECO, NASCIMENTO VALUES (?, ?, ?, ?, ?, ?, ?);