CREATE TABLE PESSOA(ID INT PRIMARY KEY AUTO_INCREMENT, NOME VARCHAR(255), EMAIL VARCHAR(255), CPF VARCHAR(255), CNPJ VARCHAR(255),
DEPARTAMENTO VARCHAR(255), MATRICULA VARCHAR(255), TELEFONE VARCHAR(255), ENDERECO VARCHAR(255), NASCIMENTO VARCHAR(255), SOCIAL VARCHAR(255), CATEGORIA VARCHAR(255));

SELECT * FROM PESSOA;
INSERT INTO PESSOA NOME, EMAIL, CPF, CNPJ, DEPARTAMENTO, MATRICULA, TELEFONE, ENDERECO, NASCIMENTO, SOCIAL, CATEGORIA VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);